version: '3.8'



services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash entrypoint.sh
    volumes:
      - .:/app
      - static_volume:/static
      - media_volume:/media
    ports:
      - "8001:8001"
   
     
volumes:
  static_volume:
  media_volume:
